Upate linux/macos tools for bootloader

diff --git a/tools/macosx/stm32l0-upload b/tools/macosx/stm32l0-upload
--- a/tools/macosx/stm32l0-upload
+++ b/tools/macosx/stm32l0-upload
@@ -1,26 +1,124 @@
 #!/bin/bash
+#
+# arguments:
+#	[ -v for verbose, -nv for quiet; -vx / -nvx same, but exit cmd on error ]
+#	vid
+# pid
+#	path to image to download
+#	base address
+#	[optional] bootloader file
+
+VERBOSE=0
+case "$1" in
+  -v) VERBOSE=1; shift;;
+  -nv) shift;;
+  -vx) VERBOSE=1; shift;;
+  -nvx) shift;;
+  *) true;;
+esac
 
 TOOLDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)
-BASEADDR="$4"
-if [ X"$BASEADDR" = X ]; then
-  echo "Need to pass in base address as argument 4!"
+
+VIDPID=
+if [[ "$1" != "-" ]]; then
+  if [[ "$2" != "-" ]]; then
+    VIDPID="$1:$2,"
+  else
+    echo "First two args are vid/pid; both must be '-' if either is"
+    exit 1
+  fi
+elif [[ "$2" != "-" ]]; then
+  echo "First two args are vid/pid; bost must be '-' if either is"
   exit 1
 fi
 
-RETRIES=10
+FILE="$3"
+if [[ "$FILE" = "" ]]; then
+  echo "Must provide image name"
+  exit 1
+fi
+if [[ ! -r "$FILE" ]]; then
+  echo "can't find file: $FILE"
+  exit 1
+fi
 
-while [ $RETRIES -gt 0 ]
+BASEADDR="$4"
+if [[ "$BASEADDR" = "" ]]; then
+  echo "must provide base address as argument 4"
+  exit 1
+fi
+
+BOOTLOADER="$5"
+if [[ X"$BOOTLOADER" = X ]]; then
+  BOOTLOADER='-'
+fi
+
+if [[ "$BOOTLOADER" != "-" ]]; then
+  if [[ ! -r "$BOOTLOADER" ]]; then
+    echo "can't find bootloader: $BOOTLOADER"
+    exit 1
+  fi
+fi
+
+OPTREPLACING=0
+if [[ "$BOOTLOADER" != "-" ]]; then
+  # make sure load address is right.
+  if [[ "$BASEADDR" != "0x08005000" ]]; then
+    echo "can't install bootloader if you select 'basic/no bootloader' in Tools/Trusted boot"
+    exit 1
+  fi
+  OPTREPLACING=1
+elif [[ "$BASEADDR" = "0x08005000" ]]; then
+  OPTREPLACING=1
+fi
+
+if [[ $VERBOSE -ne 0 ]]; then
+  echo "Program file:   $FILE"
+  echo "Board VID:PID:  $VIDPID"
+  echo "Base address:   $BASEADDR"
+  if [[ "$BOOTLOADER" != "-" ]]; then
+    echo "Bootloader:     $BOOTLOADER"
+  elif [[ $OPTREPLACING -ne 0 ]]; then
+    echo "Bootloader:     overwriting"
+  else
+    echo "Bootloader:     using existing bootloader"
+  fi
+fi
+
+RETRIES=10
+FOUND=0
+
+while [[ $RETRIES -gt 0 ]]
 do
-    if [ "$("$TOOLDIR"/dfu-util -l 2>/dev/null | grep 0483:df11)" != "" ]
+    if [[ "$("$TOOLDIR"/dfu-util -l 2>/dev/null | grep 0483:df11)" != "" ]]
     then
-      "$TOOLDIR"/dfu-util -d "$1:$2",0x0483:0xdf11 -a 0 -s "$BASEADDR:leave" -D "$3"
-      echo "OK"
-      exit 0
+      FOUND=1
+      break
     fi
     echo $RETRIES
     RETRIES=$((RETRIES - 1))
     sleep 1;
 done
 
-echo "FAIL"
+
+if [[ $FOUND -eq 0 ]]; then
+  echo "FAIL"
+  exit 1
+fi
+
+# download
+if [[ "$BOOTLOADER" != "-" ]]; then
+  # download the bootloader, and leave in download mode.
+  if ! "$TOOLDIR"/dfu-util -d "VIDPID"0x0483:0xdf11 -a 0 -s 0x08000000 -D "$BOOTLOADER"; then
+    echo "bootloader download failed"
+    exit 1
+  fi
+fi
+
+if ! "$TOOLDIR"/dfu-util -d "VIDPID"0x0483:0xdf11 -a 0 -s "$BASEADDR:leave" -D "$FILE" ; then
+  echo "main download failed"
+  exit 1
+fi
+
+echo "OK"
 exit 0
