Improve upload scripts

diff --git a/tools/linux/stm32l0-upload b/tools/linux/stm32l0-upload
--- a/tools/linux/stm32l0-upload
+++ b/tools/linux/stm32l0-upload
@@ -1,26 +1,128 @@
 #!/bin/bash
+#
+# arguments:
+#	[ -v for verbose, -nv for quiet; -vx / -nvx same, but exit cmd on error ]
+#	vid
+# pid
+#	path to image to upload
+#	base address
+#	[optional] bootloader file
+
+PNAME="$(basename "$0")"
+
+VERBOSE=0
+case "$1" in
+  -v) VERBOSE=1; shift;;
+  -nv) shift;;
+  -vx) VERBOSE=1; shift;;
+  -nvx) shift;;
+  *) true;;
+esac
+
+function _usage {
+  echo "$PNAME:" "$@"
+  echo "usage: $PNAME [-v/-nv/-vx/-nvx] vid pid fileToUpload baseAddress [bootloaderFile]"
+  exit 1
+}
 
 TOOLDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)
-BASEADDR="$4"
-if [ X"$BASEADDR" = X ]; then
-  echo "Need to pass in base address as argument 4!"
+
+VIDPID=
+if [[ "$1" != "-" ]]; then
+  if [[ "$2" != "-" ]]; then
+    VIDPID="$1:$2,"
+  else
+    _usage "First two args are vid/pid; both must be '-' if either is"
+  fi
+elif [[ "$2" != "-" ]]; then
+  _usage "First two args are vid/pid; bost must be '-' if either is"
+fi
+
+FILE="$3"
+if [[ "$FILE" = "" ]]; then
+  _usage "Must provide image name"
+fi
+if [[ ! -r "$FILE" ]]; then
+  echo "$PNAME: can't find file to upload: $FILE"
   exit 1
 fi
 
-RETRIES=10
+BASEADDR="$4"
+if [[ "$BASEADDR" = "" ]]; then
+  _usage "must provide base address as argument 4"
+fi
 
-while [ $RETRIES -gt 0 ]
+BOOTLOADER="$5"
+if [[ X"$BOOTLOADER" = X ]]; then
+  BOOTLOADER='-'
+fi
+
+if [[ "$BOOTLOADER" != "-" ]]; then
+  if [[ ! -r "$BOOTLOADER" ]]; then
+    echo "$PNAME: can't find bootloader to upload: $BOOTLOADER"
+    exit 1
+  fi
+fi
+
+OPTREPLACING=0
+if [[ "$BOOTLOADER" != "-" ]]; then
+  # make sure load address is right.
+  if [[ "$BASEADDR" != "0x08005000" ]]; then
+    echo "can't install bootloader if you select 'basic/no bootloader' in Tools/Trusted boot"
+    exit 1
+  fi
+  OPTREPLACING=1
+elif [[ "$BASEADDR" != "0x08005000" ]]; then
+  OPTREPLACING=1
+fi
+
+if [[ $VERBOSE -ne 0 ]]; then
+  echo "Program file:   $FILE"
+  echo "Board VID:PID:  ${VIDPID%,}"
+  echo "Base address:   $BASEADDR"
+  if [[ "$BOOTLOADER" != "-" ]]; then
+    echo "Bootloader:     $BOOTLOADER"
+  elif [[ $OPTREPLACING -ne 0 ]]; then
+    echo "Bootloader:     overwriting"
+  else
+    echo "Bootloader:     using existing bootloader"
+  fi
+fi
+
+RETRIES=10
+FOUND=0
+
+while [[ $RETRIES -gt 0 ]]
 do
-    if [ "$("$TOOLDIR"/dfu-util -l 2>/dev/null | grep 0483:df11)" != "" ]
+    if [[ "$("$TOOLDIR"/dfu-util -l 2>/dev/null | grep 0483:df11)" != "" ]]
     then
-      "$TOOLDIR"/dfu-util -d "$1":"$2",0x0483:0xdf11 -a 0 -s "$BASEADDR:leave" -D "$3"
-      echo "OK"
-      exit 0
+      FOUND=1
+      break
     fi
     echo $RETRIES
     RETRIES=$((RETRIES - 1))
     sleep 1;
 done
 
-echo "FAIL"
+
+if [[ $FOUND -eq 0 ]]; then
+  echo "Didn't find device for upload"
+  exit 1
+fi
+
+# upload
+if [[ "$BOOTLOADER" != "-" ]]; then
+  # upload the bootloader, and leave in upload mode.
+  if ! "$TOOLDIR"/dfu-util -d "VIDPID"0x0483:0xdf11 -a 0 -s 0x08000000 -D "$BOOTLOADER"; then
+    echo "bootloader upload failed"
+    exit 1
+  fi
+fi
+
+if ! "$TOOLDIR"/dfu-util -d "VIDPID"0x0483:0xdf11 -a 0 -s "$BASEADDR:leave" -D "$FILE" ; then
+  echo "main upload failed"
+  exit 1
+fi
+
+echo "OK"
 exit 0
diff --git a/tools/macosx/stlink_upload b/tools/macosx/stlink_upload
--- a/tools/macosx/stlink_upload
+++ b/tools/macosx/stlink_upload
@@ -3,9 +3,11 @@
 # arguments:
 #	[ -v for verbose, -nv for quiet; -vx / -nvx same, but exit cmd on error ]
 #	full path to STLINK tools
-#	path to image to download
+#	path to image to upload
 #	base address
 #	[optional] bootloader file
+
+PNAME="$(basename "$0")"
 
 VERBOSE=0
 case "$1" in
@@ -19,7 +21,20 @@ esac
 # exit on uncaught error
 set -e
 
-TOOLDIR="$1/tools"
+function _usage {
+  echo "$PNAME:" "$@"
+  echo "usage: $PNAME [-v/-nv/-vx/-nvx] tooldir fileToUpload baseAddress [bootloaderFile]"
+  exit 1
+}
+
+if [[ "$1" == "" ]]; then
+  _usage "missing tooldir"
+fi
+
+# strip trailing slashes, and append /tools
+TOOLDIR="${1%%/}/tools"
+
+# add platform-specific portion
 if [[ "$(uname)" = "Darwin" ]]; then
     TOOLDIR="$TOOLDIR/macosx"
 else
@@ -28,18 +43,15 @@ fi
 
 FILE="$2"
 if [[ "$FILE" = "" ]]; then
-  echo "Must provide image name"
-  exit 1
+  _usage "Must provide image name"
 fi
 if [[ ! -r "$FILE" ]]; then
-  echo "can't find file: $FILE"
-  exit 1
+  _usage "can't find file: $FILE"
 fi
 
 BASEADDR="$3"
 if [[ "$BASEADDR" = "" ]]; then
-  echo "must provide base address as argument 3"
-  exit 1
+  _usage "must provide base address as argument 3"
 fi
 
 BOOTLOADER="$4"
@@ -49,7 +61,7 @@ fi
 
 if [[ "$BOOTLOADER" != "-" ]]; then
   if [[ ! -r "$BOOTLOADER" ]]; then
-    echo "can't find bootloader: $BOOTLOADER"
+    echo "$PNAME: can't find bootloader: $BOOTLOADER"
     exit 1
   fi
 fi
@@ -83,9 +95,12 @@ fi
 
 # cater to system differences
 if [[ "$(uname)" = "Darwin" ]]; then
-    DYLD_LIBRARY_PATH="$TOOLDIR/stlink/lib"
-elif [[ "$(uname -m)" = "x86_64" ]]; then
+    export DYLD_LIBRARY_PATH="$TOOLDIR/stlink/lib"
+else
+  if [[ "$(uname -m)" = "x86_64" ]]; then
     TOOLDIR="$(dirname "$TOOLDIR")/linux64"
+  fi
+  export LD_LIBRARY_PATH="$TOOLDIR/stlink/lib"
 fi
 
 # upload the bootloader
diff --git a/tools/macosx/stm32l0-upload b/tools/macosx/stm32l0-upload
--- a/tools/macosx/stm32l0-upload
+++ b/tools/macosx/stm32l0-upload
@@ -4,9 +4,11 @@
 #	[ -v for verbose, -nv for quiet; -vx / -nvx same, but exit cmd on error ]
 #	vid
 # pid
-#	path to image to download
+#	path to image to upload
 #	base address
 #	[optional] bootloader file
+
+PNAME="$(basename "$0")"
 
 VERBOSE=0
 case "$1" in
@@ -17,6 +19,12 @@ case "$1" in
   *) true;;
 esac
 
+function _usage {
+  echo "$PNAME:" "$@"
+  echo "usage: $PNAME [-v/-nv/-vx/-nvx] vid pid fileToUpload baseAddress [bootloaderFile]"
+  exit 1
+}
+
 TOOLDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)
 
 VIDPID=
@@ -24,28 +32,24 @@ if [[ "$1" != "-" ]]; then
   if [[ "$2" != "-" ]]; then
     VIDPID="$1:$2,"
   else
-    echo "First two args are vid/pid; both must be '-' if either is"
-    exit 1
+    _usage "First two args are vid/pid; both must be '-' if either is"
   fi
 elif [[ "$2" != "-" ]]; then
-  echo "First two args are vid/pid; bost must be '-' if either is"
-  exit 1
+  _usage "First two args are vid/pid; bost must be '-' if either is"
 fi
 
 FILE="$3"
 if [[ "$FILE" = "" ]]; then
-  echo "Must provide image name"
-  exit 1
+  _usage "Must provide image name"
 fi
 if [[ ! -r "$FILE" ]]; then
-  echo "can't find file: $FILE"
+  echo "$PNAME: can't find file to upload: $FILE"
   exit 1
 fi
 
 BASEADDR="$4"
 if [[ "$BASEADDR" = "" ]]; then
-  echo "must provide base address as argument 4"
-  exit 1
+  _usage "must provide base address as argument 4"
 fi
 
 BOOTLOADER="$5"
@@ -55,7 +59,7 @@ fi
 
 if [[ "$BOOTLOADER" != "-" ]]; then
   if [[ ! -r "$BOOTLOADER" ]]; then
-    echo "can't find bootloader: $BOOTLOADER"
+    echo "$PNAME: can't find bootloader to upload: $BOOTLOADER"
     exit 1
   fi
 fi
@@ -68,13 +72,13 @@ if [[ "$BOOTLOADER" != "-" ]]; then
     exit 1
   fi
   OPTREPLACING=1
-elif [[ "$BASEADDR" = "0x08005000" ]]; then
+elif [[ "$BASEADDR" != "0x08005000" ]]; then
   OPTREPLACING=1
 fi
 
 if [[ $VERBOSE -ne 0 ]]; then
   echo "Program file:   $FILE"
-  echo "Board VID:PID:  $VIDPID"
+  echo "Board VID:PID:  ${VIDPID%,}"
   echo "Base address:   $BASEADDR"
   if [[ "$BOOTLOADER" != "-" ]]; then
     echo "Bootloader:     $BOOTLOADER"
@@ -102,21 +106,21 @@ done
 
 
 if [[ $FOUND -eq 0 ]]; then
-  echo "FAIL"
+  echo "Didn't find device for upload"
   exit 1
 fi
 
-# download
+# upload
 if [[ "$BOOTLOADER" != "-" ]]; then
-  # download the bootloader, and leave in download mode.
+  # upload the bootloader, and leave in upload mode.
   if ! "$TOOLDIR"/dfu-util -d "VIDPID"0x0483:0xdf11 -a 0 -s 0x08000000 -D "$BOOTLOADER"; then
-    echo "bootloader download failed"
+    echo "bootloader upload failed"
     exit 1
   fi
 fi
 
 if ! "$TOOLDIR"/dfu-util -d "VIDPID"0x0483:0xdf11 -a 0 -s "$BASEADDR:leave" -D "$FILE" ; then
-  echo "main download failed"
+  echo "main upload failed"
   exit 1
 fi
 
